#!/bin/bash
subzone=$(echo $1 | cut -d "." -f 1-2)
bestaand=$(dig +short $subzone.milo-claes.sb.uclllabs.be)

if [ -n "$bestaand" ]; then
                if [ $bestaand == "193.191.177.193" ]; then
                        echo "
                        <VirtualHost *:80>
                                ServerAdmin root@milo-claes.sb.uclllabs.be
                                ServerName $1
                                DocumentRoot /var/www/html/VhostsFromMrtScript/www.$subzone
                                ErrorLog ${APACHE_LOG_DIR}/$subzone-error.log
                                CustomLog ${APACHE_LOG_DIR}/$subzone-access.log combined
                        </VirtualHost>
                        " > /etc/apache2/sites-available/MRT.$subzone.conf;
                        cd /var/www/html/VhostsFromMrtScript
                        mkdir www.$subzone
                        cd www.$subzone
                        echo welcome $subzone >> index.html;
                        cd

                        a2ensite MRT.$subzone.conf;
                        systemctl reload apache2;
                else
                        echo Gelieve een geldige subzone mee te geven;
                fi
else
        echo Gelieve een geldige subzone mee te geven;
fi
